service: customer-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 128
  timeout: 10
  environment:
    DYNAMO_TABLE: customers

resources:
  Resources:
    CustomersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: customers
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  createCustomer:
    handler: src/handlers/createCustomer.handler
    events:
      - http:
          path: customers
          method: post

  getCustomer:
    handler: src/handlers/getCustomer.handler
    events:
      - http:
          path: customers/{id}
          method: get

  updateCustomer:
    handler: src/handlers/updateCustomer.handler
    events:
      - http:
          path: customers/{id}
          method: put

  deleteCustomer:
    handler: src/handlers/deleteCustomer.handler
    events:
      - http:
          path: customers/{id}
          method: delete

  listCustomers:
    handler: src/handlers/listCustomers.handler
    events:
      - http:
          path: customers
          method: get
